version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "remote-monitoring-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2f00z5z1cbid"
s3_prefix = "remote-monitoring-service"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "PrivateSubnets=\"/caregem/VpcSubnet\" LambdaSecurityGroupId=\"/caregem/VpcSg\" AuthorizerLambdaArn=\"/caregem/AuthorizerLambdaArn\" Stage=\"/caregem/Stage\" CognitoUserPool=\"/caregem/CognitoUserPool\" AwsRegion=\"/caregem/AwsRegion\" UserProfileTableName=\"/caregem/UserProfileTableName\" MysqlSecret=\"/caregem/MysqlSecret\" AccessLogArn=\"/caregem/AccessLogArn\""
image_repositories = []
