version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "misc-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-10ghuq43w5w9b"
s3_prefix = "misc-service"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "PrivateSubnets=\"subnet-04e151699aa86c464,subnet-02a7c6ca7897b39d6\" LambdaSecurityGroupId=\"sg-0ef323b9528c97c70\" AuthorizerLambdaArn=\"arn:aws:lambda:us-east-2:455743001475:function:CustomAuthorizerLambda\""
image_repositories = []
